/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dateisystemerfassung;

import java.awt.event.KeyEvent;

/**
 *
 * @author sunny
 */
public class AusgabeUI extends javax.swing.JFrame {

    Dateisystem dS = new Dateisystem();

    /**
     * Creates new form DateisystemAusgeben
     */
    public AusgabeUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBeschreibung = new javax.swing.JLabel();
        txtUsereingabe = new javax.swing.JTextField();
        btnSuchen = new javax.swing.JButton();
        lblAusgabe = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAusgabe = new javax.swing.JTextArea();
        btnZurueck = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblBeschreibung.setText("Suche nach:");

        txtUsereingabe.setText("Ein leeres Feld gibt das gesamte Dateisystem aus");
        txtUsereingabe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsereingabeMouseClicked(evt);
            }
        });
        txtUsereingabe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsereingabeActionPerformed(evt);
            }
        });
        txtUsereingabe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsereingabeKeyPressed(evt);
            }
        });

        btnSuchen.setText("Suchen");
        btnSuchen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuchenActionPerformed(evt);
            }
        });

        lblAusgabe.setText("Ausgabe:");

        txtAusgabe.setEditable(false);
        txtAusgabe.setColumns(20);
        txtAusgabe.setRows(5);
        jScrollPane1.setViewportView(txtAusgabe);

        btnZurueck.setText("Zurück");
        btnZurueck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZurueckActionPerformed(evt);
            }
        });

        lblStatus.setText("Status:");
        lblStatus.setToolTipText("");

        txtStatus.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtUsereingabe)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblBeschreibung)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(lblStatus)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSuchen)
                        .addGap(73, 73, 73)
                        .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addComponent(btnZurueck)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAusgabe)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBeschreibung, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtUsereingabe, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSuchen, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnZurueck, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblAusgabe, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuchenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuchenActionPerformed
        String userabfrage = txtUsereingabe.getText();
        dS.dSsGet.clear();
        txtAusgabe.setText("");
        txtStatus.setText("");
        dS.getAllByName(userabfrage);
        String ausgabe = "";
        for (int i = 0; i < dS.dSsGet.size(); i++) {
            ausgabe = ausgabe.concat(dS.dSsGet.get(i).toString());
            txtAusgabe.setText(ausgabe);
        }
        if (ausgabe.equals("")) {
            txtStatus.setText("Weder Verzeichnis noch Datei gefunden !");
        }
    }//GEN-LAST:event_btnSuchenActionPerformed

    private void txtUsereingabeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsereingabeActionPerformed

    }//GEN-LAST:event_txtUsereingabeActionPerformed

    private void txtUsereingabeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsereingabeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String userabfrage = txtUsereingabe.getText();
            dS.dSsGet.clear();
            txtAusgabe.setText("");
            txtStatus.setText("");
            dS.getAllByName(userabfrage);
            String ausgabe = "";
            for (int i = 0; i < dS.dSsGet.size(); i++) {
                ausgabe = ausgabe.concat(dS.dSsGet.get(i).toString());
                txtAusgabe.setText(ausgabe);
            }
            if (ausgabe.equals("")) {
                txtStatus.setText("Weder Verzeichnis noch Datei gefunden !");
            }
        }
    }//GEN-LAST:event_txtUsereingabeKeyPressed

    private void btnZurueckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZurueckActionPerformed
        new StartUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnZurueckActionPerformed

    private void txtUsereingabeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsereingabeMouseClicked
        txtUsereingabe.setText("");
    }//GEN-LAST:event_txtUsereingabeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AusgabeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AusgabeUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSuchen;
    private javax.swing.JButton btnZurueck;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAusgabe;
    private javax.swing.JLabel lblBeschreibung;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTextArea txtAusgabe;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtUsereingabe;
    // End of variables declaration//GEN-END:variables
}
