/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dateisystemerfassung;

import java.awt.event.KeyEvent;
import java.util.regex.Pattern;

/**
 *
 * @author sunny
 */
public class EingabeUI extends javax.swing.JFrame {

    Dateisystem dS = new Dateisystem();

    /**
     * Creates new form DateisystemErfassenUI
     */
    public EingabeUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBeschreibung = new javax.swing.JLabel();
        txtUsereingabe = new javax.swing.JTextField();
        btnSpeichern = new javax.swing.JButton();
        btnZurueck = new javax.swing.JButton();
        txtStatus = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblBeschreibung.setText("Zu speichernden Pfad angeben:");

        txtUsereingabe.setText("Bsp.: C:\\Windows");
        txtUsereingabe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsereingabeMouseClicked(evt);
            }
        });
        txtUsereingabe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsereingabeKeyPressed(evt);
            }
        });

        btnSpeichern.setText("Speichern");
        btnSpeichern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpeichernActionPerformed(evt);
            }
        });

        btnZurueck.setText("Zurück");
        btnZurueck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZurueckActionPerformed(evt);
            }
        });

        txtStatus.setEditable(false);

        lblStatus.setText("Status:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUsereingabe)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBeschreibung)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSpeichern)
                        .addGap(71, 71, 71)
                        .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addComponent(btnZurueck)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(lblStatus)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBeschreibung, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtUsereingabe, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSpeichern, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnZurueck, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSpeichernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpeichernActionPerformed
        String usereingabe = txtUsereingabe.getText();
        String[] pfadsegmente = usereingabe.split(Pattern.quote("\\"));
        dS.getdSsWalk().clear();
        dS.fileSystemReader(pfadsegmente[pfadsegmente.length - 1], usereingabe);
        if (dS.getdSsWalk().isEmpty()) {
            txtStatus.setText("Der angegebene Pfad existiert nicht !");
        } else {
            dS.dbTableDelete();
            dS.dbTableCreate();
            dS.insert();
            txtStatus.setText("Das Dateisystem wurde erfolgreich gespeichert");
        }
    }//GEN-LAST:event_btnSpeichernActionPerformed

    private void btnZurueckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZurueckActionPerformed
        new StartUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnZurueckActionPerformed

    private void txtUsereingabeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsereingabeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String usereingabe = txtUsereingabe.getText();
            String[] pfadsegmente = usereingabe.split(Pattern.quote("\\"));
            dS.getdSsWalk().clear();
            dS.fileSystemReader(pfadsegmente[pfadsegmente.length - 1], usereingabe);
            if (dS.getdSsWalk().isEmpty()) {
                txtStatus.setText("Der angegebene Pfad existiert nicht !");
            } else {
                dS.dbTableDelete();
                dS.dbTableCreate();
                dS.insert();
                txtStatus.setText("Das Dateisystem wurde erfolgreich gespeichert");
            }
        }
    }//GEN-LAST:event_txtUsereingabeKeyPressed

    private void txtUsereingabeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsereingabeMouseClicked
        txtUsereingabe.setText("");
    }//GEN-LAST:event_txtUsereingabeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EingabeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new EingabeUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSpeichern;
    private javax.swing.JButton btnZurueck;
    private javax.swing.JLabel lblBeschreibung;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtUsereingabe;
    // End of variables declaration//GEN-END:variables
}
